function About() {

  return (
    <div style={{
      minHeight: '100vh',
      background: 'url(/bg-home.png) center / cover no-repeat',
      backgroundColor: '#1a1815',
      padding: '3rem 1rem',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'flex-start'
    }}>
      <div style={{
        maxWidth: '32rem',
        width: '100%',
        background: '#f4ece0',
        borderRadius: '4px',
        boxShadow: '0 4px 12px rgba(0,0,0,0.2), 0 8px 24px rgba(0,0,0,0.15)',
        overflow: 'hidden'
      }}>
        {/* Header */}
        <div style={{
          padding: '1.25rem',
          display: 'flex',
          justifyContent: 'center'
        }}>
          <h1 style={{
            fontFamily: "'Archivo Black', sans-serif",
            fontSize: '1.3rem',
            fontWeight: 400,
            color: '#2a2825',
            textTransform: 'uppercase',
            letterSpacing: '0.02em',
            margin: 0,
            padding: '0.6rem 1.5rem',
            position: 'relative',
            background: 'rgba(120, 45, 40, 0.38)',
            clipPath: 'polygon(10px 0%, calc(100% - 10px) 0%, 100% 10px, 100% calc(100% - 10px), calc(100% - 10px) 100%, 10px 100%, 0% calc(100% - 10px), 0% 10px)'
          }}>About</h1>
        </div>

        {/* Body */}
        <div style={{
          padding: '1rem 1.5rem 1.5rem',
          background: '#f4ece0'
        }}>
          <div style={{
            background: '#f8f5f0',
            borderRadius: '3px',
            padding: '1rem 1.1rem',
            border: '1px solid #e0d8cc',
            marginBottom: '1rem'
          }}>
            <h2 style={{
              fontFamily: "'Archivo Black', sans-serif",
              fontSize: '0.7rem',
              fontWeight: 400,
              textTransform: 'uppercase',
              letterSpacing: '0.1em',
              color: '#2a2825',
              margin: '0 0 0.8rem 0',
              padding: '0.4rem 0.8rem',
              background: 'rgba(120, 45, 40, 0.25)',
              display: 'inline-block',
              borderRadius: '2px'
            }}>What is this?</h2>
            <p style={{
              fontFamily: "'Source Serif 4', Georgia, serif",
              fontSize: '0.95rem',
              lineHeight: 1.6,
              color: '#2a2825',
              margin: 0
            }}>
              Enter your name, upload a photo (or don't), and get a unique baseball scouting report 
              with 5-tool grades.
            </p>
          </div>

          <div style={{
            background: '#f8f5f0',
            borderRadius: '3px',
            padding: '1rem 1.1rem',
            border: '1px solid #e0d8cc'
          }}>
            <h2 style={{
              fontFamily: "'Archivo Black', sans-serif",
              fontSize: '0.7rem',
              fontWeight: 400,
              textTransform: 'uppercase',
              letterSpacing: '0.1em',
              color: '#2a2825',
              margin: '0 0 0.8rem 0',
              padding: '0.4rem 0.8rem',
              background: 'rgba(120, 45, 40, 0.25)',
              display: 'inline-block',
              borderRadius: '2px'
            }}>How does it work?</h2>
            <p style={{
              fontFamily: "'Source Serif 4', Georgia, serif",
              fontSize: '0.95rem',
              lineHeight: 1.6,
              color: '#2a2825',
              margin: 0
            }}>
              Scouting reports are generated by a quantized 2.7B Llama model fine-tuned on{' '}
              <a 
                href="https://www.fangraphs.com" 
                target="_blank" 
                rel="noopener noreferrer"
                style={{ color: '#2a3038', textDecoration: 'underline' }}
              >
                FanGraphs
              </a>{' '}
              prospect writeups. The 5-tool grades are generated with the assistance of{' '}
              <a 
                href="https://www.anthropic.com/claude" 
                target="_blank" 
                rel="noopener noreferrer"
                style={{ color: '#2a3038', textDecoration: 'underline' }}
              >
                Claude
              </a>
              , Anthropic's AI, which predicts ratings on the 20–80 scouting scale.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default About;
